language: php

sudo: required

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

go:
  - "1.11.x"

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source
#  - go get "github.com/spiral/goridge"
#  - cp -r * $GOPATH/src/github.com/spiral/goridge
  - go mod tidy
#  - go get "github.com/pkg/errors"
#  - go get "github.com/stretchr/testify/assert"
  - go build tests/server.go


before_script:
  - ./server &
  - ./server server.sock &

env:
- GO111MODULE=on

script:
  - go build
  - go test
  - vendor/bin/phpunit --coverage-clover=clover.xml

after_script:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar --verbose --config .coveralls.yml
